# version: 1.0.0

palette = 'dracula'

add_newline = true
continuation_prompt = "[    ❯❯ ](dimmed white)"

format = """
[╭─](dimmed white)\
$nix_shell\
$container\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$os\
$directory\
$git_branch\
$git_status\
$git_metrics\
$hg_branch\
([](bg:prev_bg fg:background2)[ ](bg:prev_fg)\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python${custom.novenv}\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal)\
[](fg:background bg:prev_bg)\
[≻$fill≺](dimmed white)\
[](bg:background fg:background2)\
$battery\
$time\
[](fg:background bg:background2)\
[─╮](dimmed white)
[╰─ ](dimmed white)\
$character❯ \
"""

right_format = """
$custom\
$status\
$cmd_duration \
[─╯](dimmed white)
"""


[palettes.dracula]

background='#282A36'
background2='#454758'
background3='#24667d'
background4='#0284a1'

foreground='#F8F8F2'
selection='#44475A'
comment='#6272A4'
red='#FF5555'
orange='#FFB86C'
yellow='#F1FA8C'
green='#50FA7B'
purple='#BD93F9'
cyan='#8BE9FD'
pink='#FF79C6'


[fill]
symbol = '─'


[os]
disabled = false
format = " $symbol [](fg:background4)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[character]
format = "$symbol "
success_symbol = "[✓](bold italic bright-yellow)"
error_symbol = "[✗](italic purple)"
vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bright-yellow bold italic bg:prev_bg"
style_root = "purple bold italic bg:prev_bg"
format = "[⭘ $user]($style) "
disabled = false
show_always = false


[jobs]
format = "[$symbol$number]($style)"
style = "white bg:prev_bg"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta bg:prev_bg)"
disabled = false


[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
home_symbol = "~"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo=false
read_only = " ◈"
use_os_path_sep = true
style = "white bg:background4"
repo_root_style = 'bold white bg:prev_bg'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = "[](bg:prev_bg fg:background3)[$symbol $branch(:$remote_branch)]($style)"
symbol = ""
style = "italic pink bg:background3"
truncation_symbol = "⋯"
truncation_length = 40
only_attached = true


[git_status]
style = "bold italic pink bg:prev_bg"
format = "([ $ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed ]($style))"
conflicted = "[◪◦](italic bright-magenta bg:prev_bg)"
ahead = "[▴│[${count}](bold white bg:prev_bg)│](italic green bg:prev_bg)"
behind = "[▿│[${count}](bold white bg:prev_bg)│](italic red bg:prev_bg)"
diverged = "[◇ ▴┤[${ahead_count}](regular white bg:prev_bg)│▿┤[${behind_count}](regular white bg:prev_bg)│](italic bright-magenta bg:prev_bg)"
untracked = "[◌◦](italic pink bg:prev_bg)"
stashed = "[◃◈](italic white bg:prev_bg)"
modified = "[●◦](italic pink bg:prev_bg)"
staged = "[▪┤[$count](bold white bg:prev_bg)│](italic bright-cyan bg:prev_bg)"
renamed = "[◎◦](italic bright-blue bg:prev_bg)"
deleted = "[✕](italic red bg:prev_bg)"

[git_metrics]
format = '([▴$added]($added_style))([ ▿$deleted]($deleted_style))'
added_style = 'italic green bg:prev_bg'
deleted_style = 'italic red bg:prev_bg'
ignore_submodules = true
disabled = false

[deno]
format = " [deno](italic) [∫ $version](green bold bg:prev_bg)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold bright-yellow bg:prev_bg"

[nodejs]
format = "[ node](italic) [◫ ($version)](bold bright-green bg:prev_bg)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = "[ (${symbol} ${version} venv:$virtualenv)]($style)"
symbol = ""
python_binary = ["python3", "python"]
version_format = "${raw}"
style = "bold blue bg:prev_bg"

[custom.novenv]
description = "show indicator when venv is missing"
command = """
print "NO VENV"
"""
when = '''[[ -f "requirements.txt" || -f "pyproject.toml" || -f "poetry.lock" || -f "Pipfile" ]] && [[ -z "$VIRTUAL_ENV" ]]'''
format = '[($output)](bold red bg:prev_bg)'

[ruby]
format = "[ rb](italic bg:prev_bg) [${symbol}${version}]($style)"
symbol = "◆ "
version_format = "${raw}"
style = "bold red bg:prev_bg"

[rust]
format = "[ rs](italic bg:prev_bg) [$symbol$version]($style)"
symbol = "⊃ "
version_format = "${raw}"
style = "bold red bg:prev_bg"

[package]
format = "[$symbol $version]($style)"
version_format = "v${raw}"
symbol = "󰏗"
style = "dimmed yellow italic bold bg:prev_bg"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = "◁ "
style = "bold bright-red"
version_format = "${raw}"

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = "▲ "

[buf]
symbol = "■ "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = "◯ "
format = " conda [$symbol$environment]($style)"

[dart]
symbol = "◁◅ "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = "◧ "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = "△ "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = "◩ "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = "∩ "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = "❯λ "
format = " hs [$symbol($version )]($style)"

[java]
symbol = "∪ "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = "◎ "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "▪▫▪ "
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = "▴▲▴ "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = '✶'
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"


# RIGHT
[battery]
format = "[$symbol$percentage ]($style)"
full_symbol = "󰮭"
charging_symbol = "[↑](italic bold green bg:prev_fg)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red bg:background2"

[[battery.display]]
threshold = 60
style = "italic bright-purple bg:background2"

[[battery.display]]
threshold = 100
style = "italic cyan bg:background2"

[time]
disabled = false
format = "[$time ]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic white bg:background2"



# RIGHT BOTTOM
[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[◄ $duration](italic white)"
